spring:
  application:
    name: "spring-ai"
  threads:
    virtual:
      enabled: true
  ai:
    ollama:
      base-url: "${AI_OLLAMA_BASE_URL:http://localhost:11434}"
      chat:
        model: "${AI_OLLAMA_CHAT_MODEL_NAME:llama3.2:3b}"
      embedding:
        options:
          model: "${AI_OLLAMA_EMBEDDING_MODEL_NAME:mxbai-embed-large}"
    vectorstore:
      pgvector:
        index-type: "${AI_OLLAMA_VECTOR_INDEX_TYPE:HNSW}"
        dimension: "${AI_OLLAMA_EMBEDDING_DIMENSION:1024}"
        distance-type: COSINE_DISTANCE
        batching-strategy: TOKEN_COUNT # Optional: Controls how documents are batched for embedding
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
        schema-validation: true
  flyway:
    enabled: ${AI_CREATE_PG_VECTOR_DATABASE:true}
    placeholders:
      embeddingDimension: ${spring.ai.vectorstore.pgvector.dimension}
      vectorIndexType: ${spring.ai.vectorstore.pgvector.index-type}
  datasource:
    hikari:
      jdbc-url: "${DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydatabase}"
      username: "${DATASOURCE_USERNAME:myuser}"
      password: "${DATASOURCE_PASSWORD:secret}"
      maximum-pool-size: 30
      driver:
        class:
          name: org.postgresql.Driver
app:
  ai:
    engine: "${APP_AI_ENGINE:ollama}"

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{x_request_id:-no_request_id} %m %wEx %n'
  level:
    web: INFO
    org:
      springframework:
        ai: INFO

logback.access:
  enabled: "${ACCESS_LOG_ENABLED:true}"
  tee-filter:
    enabled: "${ACCESS_TEE_LOG_ENABLED:true}"