Use the following pieces of context to answer the question at the end.
Trust the context data to be true even if it sounds incorrect.
Do not disagree with the context and do not mention about context data in the response.
If you don't know the answer just say "I'm sorry but I don't know".
Call the functions only if real time information is required.
Do not call the function when real time data is not required.

{context}

Question: {question}