name: 'CI-main'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature-*

jobs:
  master-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # default 360
    steps:
    - uses: actions/checkout@v4
    - name: Install Java 21
      uses: actions/setup-java@v1
      with:
        java-version: '21'
        java-package: jdk
        architecture: x64
    - name: 'Install dependencies'
      run: |
        ./ci-install-dependencies.sh
    - name: 'Install Maven dependencies'
      run: |
        ./ci-install-maven-dependencies.sh
    - name: 'CI Build Command'
      timeout-minutes: 20
      env:
        OPEN_AI_KEY: ${{ secrets.OPEN_AI_KEY }}
        INTEGRATION_TEST_ACTIVE_PROFILES: 'it,openai'
      run: |
        ./ci-build.sh
