name: 'CI-main'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature-*

jobs:
  master-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # default 360
    steps:
    - uses: actions/checkout@v4
    - name: Install Java 21
      uses: actions/setup-java@v1
      with:
        java-version: '21'
        java-package: jdk
        architecture: x64
    - name: 'Install dependencies'
      run: |
        ./ci-install-dependencies.sh
    - name: 'CI Build Command'
      timeout-minutes: 20
      env:
        AWS_AI_ACCESS_KEY_ID: ${{ secrets.AWS_AI_ACCESS_KEY_ID }}
        AWS_AI_SECRET_ACCESS_KEY: ${{ secrets.AWS_AI_SECRET_ACCESS_KEY }}
        APP_AI_CHAT_PROVIDER: 'aws'
        APP_AI_EMBEDDING_PROVIDER: 'aws'
      run: |
        ./ci-build.sh
